<<<<<<< HEAD
name: clean_architecture_tdd_course
description: TDD Clean Architecture for Flutter
=======
name: flutter_tdd_clean_architecture_code_alberto
description: A new Flutter project.
>>>>>>> 50ca362eadb408b155ea9cf403107f2e7f94e42e

version: 1.0.0+1

environment:
<<<<<<< HEAD
  sdk: '>=2.6.0 <3.0.0'
=======
  sdk: ">=2.7.0 <3.0.0"
>>>>>>> 50ca362eadb408b155ea9cf403107f2e7f94e42e

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^6.0.0
  # Value equality
  equatable: ^2.0.0
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  # Local cache
  shared_preferences: ^0.5.6
=======
  
  # Service locator
  get_it: ^6.0.0
  
  # Bloc for state management
  flutter_bloc: ^6.1.3
  
  # Value equality
  equatable: ^2.0.0
  
  # Functional programming thingies
  dartz: ^0.9.2
  
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.13.0

  # Local cache
  shared_preferences: ^2.0.4

  cupertino_icons: ^1.0.0
>>>>>>> 50ca362eadb408b155ea9cf403107f2e7f94e42e

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
  mockito: ^4.1.1
=======
  mockito: ^4.1.2
  bloc_test: ^7.1.0

>>>>>>> 50ca362eadb408b155ea9cf403107f2e7f94e42e

flutter:
  uses-material-design: true
